import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html'
})
export class AppComponent {
  autocompleteItems = [
    { president: 'George Washington', party: 'No Party' },
    { president: 'John Adams', party: 'Federalist' },
    { president: 'Thomas Jefferson', party: 'Democratic-Republican' },
    { president: 'James Madison', party: 'Democratic-Republican' },
    { president: 'James Monroe', party: 'Democratic-Republican' },
    { president: 'John Quincy Adams', party: 'Democratic-Republican' },
    { president: 'Andrew Jackson', party: 'Democratic' },
    { president: 'Martin Van Buren', party: 'Democratic' },
    { president: 'William Henry Harrison', party: 'Whig' },
    { president: 'John Tyler', party: 'Whig' },
    { president: 'James K. Polk', party: 'Democratic' },
    { president: 'Zachary Taylor', party: 'Whig' },
    { president: 'Millard Fillmore', party: 'Whig' },
    { president: 'Franklin Pierce', party: 'Democratic' },
    { president: 'James Buchanan', party: 'Democratic' },
    { president: 'Abraham Lincoln', party: 'Republican' },
    { president: 'Andrew Johnson', party: 'Democratic' },
    { president: 'Ulysses S. Grant', party: 'Republican' },
    { president: 'Rutherford B. Hayes', party: 'Republican' },
    { president: 'James A. Garfield', party: 'Republican' },
    { president: 'Chester A. Arthur', party: 'Republican' },
    { president: 'Grover Cleveland', party: 'Democratic' },
    { president: 'Benjamin Harrison', party: 'Republican' },
    { president: 'Grover Cleveland', party: 'Democratic' },
    { president: 'William McKinley', party: 'Republican' },
    { president: 'Theodore Roosevelt', party: 'Republican' },
    { president: 'William Howard Taft', party: 'Republican' },
    { president: 'Woodrow Wilson', party: 'Democratic' },
    { president: 'Warren G. Harding', party: 'Republican' },
    { president: 'Calvin Coolidge', party: 'Republican' },
    { president: 'Herbert Hoover', party: 'Republican' },
    { president: 'Franklin D. Roosevelt', party: 'Democratic' },
    { president: 'Harry S. Truman', party: 'Democratic' },
    { president: 'Dwight D. Eisenhower', party: 'Republican' },
    { president: 'John F. Kennedy', party: 'Democratic' },
    { president: 'Lyndon B. Johnson', party: 'Democratic' },
    { president: 'Richard Nixon', party: 'Republican' },
    { president: 'Gerald Ford', party: 'Republican' },
    { president: 'Jimmy Carter', party: 'Democratic' },
    { president: 'Ronald Reagan', party: 'Republican' },
    { president: 'George H. W. Bush', party: 'Republican' },
    { president: 'Bill Clinton', party: 'Democratic' },
    { president: 'George W. Bush', party: 'Republican' },
    { president: 'Barack Obama', party: 'Democratic' },
    { president: 'Donald J. Trump', party: 'Republican' }
  ];
}
